apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.5.0
    helm:
      values: |
        cluster_env: dev
        controller:
          type: daemonset
        alloy:
          mounts:
            varlog: true
            dockercontainers: true
          configMap:
            content: |
              logging {
                level = "info"
                format = "logfmt"
              }

              discovery.kubernetes "pods" {
                role = "pod"
                selectors {
                  role = "pod"
                  field = "spec.nodeName=" + coalesce(sys.env("HOSTNAME"), constants.hostname)
                }
              }

              discovery.relabel "pods" {
                targets = discovery.kubernetes.pods.targets
                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  action = "replace"
                  target_label = "namespace"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_name"]
                  action = "replace"
                  target_label = "pod"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_container_name"]
                  action = "replace"
                  target_label = "container"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_label_app"]
                  action = "replace"
                  target_label = "app"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_label_org_id"]
                  action = "replace"
                  target_label = "org_id"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_label_project_id"]
                  action = "replace"
                  target_label = "project_id"
                }
                rule {
                  source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_name", "__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
                  action = "replace"
                  target_label = "__path__"
                  separator = "/"
                  regex = "([^/]+)/([^/]+)/([^/]+)/([^/]+)"
                  replacement = "/var/log/pods/${1}_${2}_${3}/${4}/*.log"
                }
                rule {
                  target_label = "environment"
                  replacement  = {{ .Values.cluster_env | quote }}
                }
              }

              local.file_match "pods" {
                path_targets = discovery.relabel.pods.output
              }

              loki.source.file "pods" {
                targets    = local.file_match.pods.targets
                forward_to = [loki.process.pods.receiver]
              }

              loki.process "pods" {
                stage.cri {}

                stage.json {
                  expressions = {
                    level = "level",
                  }
                }

                stage.regex {
                  expression = "\\s+(?P<level>INFO|WARN|ERROR|DEBUG|FATAL):\\s+"
                }

                stage.labels {
                  values = {
                    level = "level",
                  }
                }

                forward_to = [loki.write.default.receiver]
              }

              loki.write "default" {
                endpoint {
                  url = "http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
                }
              }
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
